### ISSUE TITLE
git also required for cloning

### ISSUE THREAD

**Issue by krismcqueen** [kaazing/gateway#10]
Perhaps this crosses the line of being pedantic, but git is also required for this project, and one would have to fork/clone the repo first before executing mvn clean install.  I suggest adding git to the requirements and then updating the steps to build with first cloning

git clone https://github.com/kaazing/gateway.distribution.git

**Comment by dpwspoon** [comment]
Git clone is no longer in README, and as such I'm closing this.  If we add the git clone steps back in then we can add this in
