### ISSUE TITLE
(doc) Doc markdown needs to use "bash" for the code type

### ISSUE THREAD

**Issue by robinzimmermann** [kaazing/gateway#124]
The [doc/troubleshooting/ts_security.md](https://github.com/kaazing/gateway/blob/develop/doc/troubleshooting/ts_security.md) doc contains the following snippet:

> \`\`\` sh-session
> 2012-02-29 10:03:56,305 INFO   session.revalidate - 
> \`\`\`

The "sh-session" code descriptor isn't recognizable by Jekyll. But "bash" is. I believe this is also recognizable by GitHub. From https://help.github.com/articles/github-flavored-markdown/:

> You can find out which keywords are valid by [perusing the languages YAML file](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml).

**Comment by michaelcretzman** [comment]
pull request: https://github.com/kaazing/gateway/pull/140
