### ISSUE TITLE
(doc) Add links to admin-reference/p_config_multicast.md

### ISSUE THREAD

**Issue by vjwang** [kaazing/gateway#134]
Add navigation to the topic admin-reference/p_config_multicast.md

**Comment by veschup** [comment]
Pull Request: 

Added xlinks to [Configure the Gateway to Use Multicast](https://github.com/kaazing/gateway/blob/develop/doc/admin-reference/p_configure_multicast.md) in these topics:
- The [broadcast service](https://github.com/veschup/gateway/blob/develop/doc/admin-reference/r_configure_gateway_service.md#broadcast) in the Examples section.
- To the "Additional Services" row in the table of [Configure KAAZING Gateway](https://github.com/veschup/gateway/blob/develop/doc/admin-reference/p_configure_gateway_files.md)

A link was already included on the index.md TOC page.
