### ISSUE TITLE
SseSameOriginIT sseIe8HttpxeConnectAndGetData fails intermittently

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#141]
````
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.27 sec <<< FAILURE! - in org.kaazing.gateway.transport.sse.SseSameOriginIT
sseIe8HttpxeConnectAndGetData(org.kaazing.gateway.transport.sse.SseSameOriginIT)  Time elapsed: 0.143 sec  <<< FAILURE!

org.junit.ComparisonFailure: Specified behavior did not match expected:<...ad "\n"
read /:.*/ "[\n"
read "\n"
read "data:Kobe is greater than Griffen\n"
read "\n"

close
closed]
> but was:<...ad "\n"
read /:.*/ "[ "]
>
````

**Comment by cmebarrow** [comment]
The k3po script is failing to synchronize between the backend stream and the client stream. This therefore means that the backend and client are potentially attempting to close their connections at the same time at the TCP level. Closing the backend connection results in closing all open clients (see BroadcastListenHandler.doSessionClosed), and the backend connection is potentially on a different I/O thread from the client.

At first we thought this was about: broadcast service should flush the data from the backend to the client before closing the client connection since BroadcastListenHandler.doSessionClosed calls (client)session.close(false). However, if the client has itself closed its own TCPConnection by that time, then the data could not possibly be written out. So I think this is more of an issue with the robot script. It needs to be fixed to use a barrier like the other scripts for that test.

**Comment by dpwspoon** [comment]
[link to script](https://github.com/kaazing/gateway/blob/26d2a903d784c87122890005fa831091777af839/transport/sse/src/test/scripts/org/kaazing/gateway/transport/sse/sse.connect.and.get.data.via.ie8.httpxe.rpt)
