### ISSUE TITLE
(doc) Typos

### ISSUE THREAD

**Issue by vjwang** [kaazing/gateway#142]
_From @vjwang on March 31, 2015 18:36_

In r_conf_service.md, the last sentence in this paragraph should be removed:

The maximum interval the Gateway waits before retrying if an attempt to connect to the SOCKS proxy fails. The Gateway initially retries after waiting for 500ms; the subsequent wait intervals are as follows: 1s, 2s, 4s, and so on up to the value of socks.retry.maximum.interval. After the maximum interval is reached, the Gateway continues to reconnect to the SOCKS proxy at the maximum interval. See sock.retry.maximum.interval.

**Comment by veschup** [comment]
This was fixed as a part of #240 (reference architecture and enterprise shield) work. 

Please close this ticket on my behalf. Thanks.
