### ISSUE TITLE
(doc) Add connect options to service defaults description

### ISSUE THREAD

**Issue by vjwang** [kaazing/gateway#143]
Connect-Options are supported in Service Defaults and needs to be added to the admin. doc.

**Comment by veschup** [comment]
Pull Request: 

**Files changed** 
- https://github.com/veschup/gateway/blob/develop/doc/admin-reference/r_configure_gateway_service_defaults.md

**Summary**
- Added connect-options to the Service-defaults reference, and replaced the lengthy listings of subelements and properties (for accept-options and mime-mapping)) with links to the Service Ref where these are already documented.  Maintaining one source of truth will keep the doc accurate and save on writer maintenance chores.
