### ISSUE TITLE
(doc) Admin guide is missing maximum-age

### ISSUE THREAD

**Issue by vjwang** [kaazing/gateway#145]
_From @dpwspoon on April 9, 2015 17:32_

Maximum age is allowed under the cross-site-constraints

from xsd
```
            <element maxOccurs="1" minOccurs="0" name="maximum-age"
                     type="nonNegativeInteger"/>
```

This will set the [Access-Control-Max-Age header](http://www.w3.org/TR/cors/#access-control-max-age-response-header) on CORS

If the value is blank the header will not be sent, meaning the maximum age is at the discretion of the client.
 

_Copied from original issue: kaazing-private/amqp.doc#28_

**Comment by vjwang** [comment]
_From @dpwspoon on April 9, 2015 17:33_

Filed the issue here under @veschup suggestion.  Ping @vjwang

**Comment by veschup** [comment]
**Pull request: _tbs_** 

I added maximum-age to:
- https://github.com/veschup/gateway/blob/develop/doc/admin-reference/r_configure_gateway_service.md (search on "maximum-age" to find the 2 additions)
- https://github.com/veschup/gateway/blob/develop/doc/admin-reference/r_configure_gateway_element_skeleton.md
- https://github.com/veschup/gateway/blob/develop/doc/admin-reference/r_configure_gateway_element_index.md
