### ISSUE TITLE
Document using /dev/random vs /dev/urandom in production environments

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/gateway#170]
See https://github.com/kaazing/gateway/pull/169 and https://github.com/kaazing/gateway/issues/167 for details

**Comment by vjwang** [comment]
@dpwspoon This needs more information. Who would use these and why?

**Comment by dpwspoon** [comment]
Both are considered secure.  dev/random is technically more random though and it works by generating random numbers using random seeds from the "entropy" of the machine it is running on (keyboard input, network input etc).  dev/random is what is used out of the box for Java, and is suitable for conventional servers.  However, some "boxs" such as VM and docker containers generate very little entropy. dev/random blocks when generating random numbers until enough entropy is available to generate a seed for a random generator. Thus this can have severe performance impacts on those machines.  For those type of systems we recommend using dev/urandom, which only regenerates the seeds when enough entropy is available.  By default, we are now shipping using dev/urandom because we do not know what type of environment the gateway will be ran on.

**Comment by robinzimmermann** [comment]
Thanks for the detailed explanation, @dpwspoon. But what is the touchpoint for customers? When they do use /dev/random or /dev/urandom in the context of Kaazing?

**Comment by dpwspoon** [comment]
If you run the gateway on a box with low entropy, (.docker container or perhaps a vm), then you want to use /dev/urandom.  All other cases you would probably want to use /dev/random but it doesn't hurt to use dev/urandom
