### ISSUE TITLE
Update to latest community to consume fixes for animal sniffer plugin

### ISSUE THREAD

**Issue by krismcqueen** [kaazing/gateway#176]
The baseline compile target for the Gateway is now 1.8. The animal sniffer plugin was consuming a java17 signature and was not compatible with Java 1.8.  Also, the animal sniffer plugin was not properly consumed in Gateway, thus not ensuring the code adhered to the supported runtime environment. The community pom has been updated to pull in a later version of animal sniffer and a java18 signature artifact, see https://github.com/kaazing/community/issues/24 and https://github.com/kaazing/community/issues/25. Once the animal sniffer fixes have been merged and released, they should be consumed in gateway to ensure enforcement of correctness in the codebase.

**Comment by krismcqueen** [comment]
under review:  https://github.com/kaazing/gateway/pull/177

**Comment by dpwspoon** [comment]
closed via https://github.com/kaazing/gateway/pull/177
