### ISSUE TITLE
WSE not working in F5 BIG-IP topologies with multiple gateways on port - BUG

### ISSUE THREAD

**Issue by apirvu** [kaazing/gateway#187]
<b>Gateway with version </b>: BYOP 4.0.8
<b>F5 BIG-IP version</b>: 11.3.0 Build 39.0 VE Trial 11.3.0-HF1

<b>Steps to reproduce:</b>
1. Have the following topologies:
 client - F5 BIG-IP - cluster of 2 Gateways
 client - F5 BIG-IP - 2 independent Gateways
BIG-IP load-balances the Gateways in the cluster.
The Virtual Server on F5 should NOT have the WS-allow iRule (which means the BIG-IP discards packets with HTTP Upgrade, thus the client should fallback to WSE).
2. Open a browser, connect to the BIG-IP external interface. Should see a Gateway demo page.
3. Go to JavaScript Demo and hit Connect, then send a message. 
4. Check the number of connections on the Gateway. The Gateway shows a connection.
5. Close the browser.

<b> Observed behavior: </b>
 It seems to be a connection, but the message is not displayed back.
Nothing happens anymore (no WS/404 error is displayed). 
After closing the browser, the connection remains open on the Gateway.

<b>Expected behavior:</b>
Since WS is not working in absence of the WS-allow iRule, the client should fallback to WSE.
When the browser is closed, the connection should also be closed from the Gateway.

<b>NOTE</b>: this happens when using default port 80 or other non-default port.
It happens in the cluster topology, and also when 2 independent Gateways are behind the F5.

Gateway Java version:

Customer:

Support Tickets & Related issues:

Verifier:

**Comment by apirvu** [comment]
NOTE: 
The above happens when ports used for connection are below 9500 (tried 80, 8000 and 9000, which failed). With port 9500, not only the connection worked, but it was WebSocket! - it didn't fallback to WSE, even though there no WS-allow rule on F5.

**Comment by apirvu** [comment]
[BUG - no WSE on port 80 QA setup independent gws.pcapng | uploaded via ZenHub](https://files.zenhub.io/5579a7c6f2e14dda72535e5b)

**Comment by apirvu** [comment]
192.168.6.160 is the F5's external address, the one accessible to the client (browser).
So we can say that 192.168.6.160 somehow represents the gateway.

**Comment by brennangaunce** [comment]
Jitu - please investigate when you have an opportunity.  I would like to identify the issue and schedule time in the next sprint to address this in 4.0.x and beyond.

**Comment by pkhanal** [comment]
@apirvu, The downstream, subsequent long polling and the upstream requests are getting 404 Not Found. 
Is it possible that Upstream & Downstream requests are forwarded to different gateway by F5 Proxy ? The Upstream & Downstream requests should be forwarded to same gateway to which Create request was forwarded. 

Nonetheless, this should have been resulted in close event fired to the application. Is the application getting close event? You should see ``Closed`` message in demo log if that is happening.

**Comment by brennangaunce** [comment]
Prashant - please go ahead and create a robot test based on your findings.

Note that a second Gateway is required to reproduce this issue, so it is almost certainly involved.  We have seen this issue at customer sites involving F5's, where the upstream and downstream are routed to different gateways.  The workaround is to use a cookie or similar (WebSocket) session based routing.

I asked Alex @apirvu  to supply wiresharks from both sides of the F5 (at the client, plus at each Gateway).  Let's make sure you have all of the diagnostic information you need.

**Comment by sbadugu** [comment]
This issue was moved to kaazing-private/gateway#22
