### ISSUE TITLE
Create a single distribution file for all environments

### ISSUE THREAD

**Issue by robinzimmermann** [kaazing/gateway#20]
Instead of two distributions (linux.tar.gz and windows.zip), we should have a single distribution which combines the scripts necessary for Linux and Windows.

For example, the `bin` directory could contain both `gateway.start` and `gateway.start.bat` scripts.

While we're at it: Shouldn't the scripts be `start-gateway.sh` and `start-gateway.bat`...?

**Comment by dpwspoon** [comment]
The line endings affect any shared filed, like gateway-config.xml, log4j, etc.

If we do consolidate, it should not be an issue for developers who will build on the platform they are using.  When we build for the release we will then need to build once on windows and once on linux/mac

**Comment by dpwspoon** [comment]
Closing as not going to fix, can reopen if we think we will change this in the future
