### ISSUE TITLE
net.sourceforge.cobertura.javancss.parser.ParseException

### ISSUE THREAD

**Issue by ahousing** [kaazing/gateway#208]
During our cobertura builds, in a couple of places we get a net.sourceforge.cobertura.javancss.parser.ParseException.  We should figure this out and fix.

**Comment by dpwspoon** [comment]
This is not causing the builds to fail AFAIK.  And is really a bug with cobertura.  We should report it to them to get a fix in.

**Comment by sbadugu** [comment]
We are not using Cobertura anymore.
