### ISSUE TITLE
Rename http.keepalive.max.connections to http.keepalive.connections in Gateway configuration

### ISSUE THREAD

**Issue by robinzimmermann** [kaazing/gateway#209]
After discussion with @jitsni, the best option seems like `http.keepalive.connections`. The lets all of the keepalive options begin with "http.keepalive". It was also felt that "max" is unneeded because that implies there is a cap on the number of connections which might be misleading to users.

**Comment by robinzimmermann** [comment]
@jfallows Please review as this is public API. It was updated in the functional spec.

**Comment by brennangaunce** [comment]
+1

**Comment by vjwang** [comment]
Added a note to @veschup's doc plan.

**Comment by robinzimmermann** [comment]
This has been approved in the functional spec. Please proceed.

**Comment by sbadugu** [comment]
Okay. It will be addressed next week.

**Comment by sbadugu** [comment]
@jitsni Can please make sure this is fixed in 4.0.9 ?

**Comment by dpwspoon** [comment]
@sbadugu, I believe this is for the http.proxy which is not in 4.x

**Comment by sbadugu** [comment]
@dpwspoon Thanks. You're right.
