### ISSUE TITLE
Remove the Session <type> from gateway documentation 

### ISSUE THREAD

**Issue by veschup** [kaazing/gateway#214]
Per David W: "The Session service is removed in 5.0 CE and EE."

**Comment by veschup** [comment]
**Removed session from:**
- [ ] [Service Reference](https://github.com/veschup/gateway/edit/develop/doc/admin-reference/r_configure_gateway_element_skeleton.md)
- [ ] [Element Index](https://github.com/veschup/gateway/blob/develop/doc/admin-reference/r_configure_gateway_element_index.md)
- [ ] [Element Skeleton](https://github.com/veschup/gateway/blob/develop/doc/admin-reference/r_configure_gateway_element_skeleton.md). Removed session:
  - From the list under "'type" at the top of the file (line 53)
  - From the description for the type element (line 103)
  - The list under ### type (line 420)
  - Removed session description, example, and notes (lines 826-847) 

**Checked for other occurrences by using grep on my local repo/directory.** find . -name "*.md" | xargs grep -l "'session'"

**Comment by veschup** [comment]
@vjwang or @michaelcretzman 
Please verify that all occurrences of the 'session' service type have been removed from the gateway repo:

- [ ] [Service Reference](https://github.com/veschup/gateway/edit/develop/doc/admin-reference/r_configure_gateway_element_skeleton.md)
  - [ ] From the list under "'type" at the top of the file (line 53)
  - [ ] From the description for the type element (line 103)
  - [ ] The list under ### type (line 420)
  - [ ] Removed session description, example, and notes (lines 826-847) 
- [ ] [Element Index](https://github.com/veschup/gateway/blob/develop/doc/admin-reference/r_configure_gateway_element_index.md)
- [ ] [Element Skeleton](https://github.com/veschup/gateway/blob/develop/doc/admin-reference/r_configure_gateway_element_skeleton.md)

**Comment by veschup** [comment]
@vjwang 
Pull Request https://github.com/kaazing/gateway/pull/218

**Comment by michaelcretzman** [comment]
Verified.

**Comment by vjwang** [comment]
Merged. Thanks!
