### ISSUE TITLE
Server API Documentation section needs updating

### ISSUE THREAD

**Issue by michaelcretzman** [kaazing/gateway#219]
Right now it is:

Server API Documentation
------------------------

-   [Server Provider Interface](http://developer.kaazing.com/documentation/5.0/apidoc/server/gateway/server/spi/index.html)
-   [JMS Server Security](http://developer.kaazing.com/documentation/jms/4.0/apidoc/server/jms/server/spi/index.html) ![This feature is available in KAAZING Gateway - Enterprise Edition](images/enterprise-feature.png)

Should be:

Server API Documentation
------------------------

-   [Server Provider Interface](http://developer.kaazing.com/documentation/5.0/apidoc/server/gateway/server/spi/index.html) ![This feature is available in KAAZING Gateway - Enterprise Edition](https://github.com/kaazing/gateway/blob/develop/doc/images/enterprise-feature.png)
- [Server Security](link to org.kaazing.gateway.server.spi.security API docs)
- [AMQP Server Security](http://developer.kaazing.com/documentation/amqp/5.0/apidoc/server/amqp/server/spi/index.html) ![This feature is available in KAAZING Gateway - Enterprise Edition](https://github.com/kaazing/gateway/blob/develop/doc/images/enterprise-feature.png)
-   [JMS Server Security](http://developer.kaazing.com/documentation/jms/5.0/apidoc/server/jms/server/spi/index.html) ![This feature is available in KAAZING Gateway - Enterprise Edition](https://github.com/kaazing/gateway/blob/develop/doc/images/enterprise-feature.png)

**Comment by veschup** [comment]
Why do we need a link to the SPI for 4.0? 
[Kaazing WebSocket Gateway - Server Service Provider Interface 4.0.0.3 API](http://developer.kaazing.com/documentation/gateway/4.0/apidoc/server/gateway/server/spi/index.html)

**Comment by michaelcretzman** [comment]
Can you clarify? I don't understand. I have a 4.0 link to the JMS SPI in my proposal because there's no 5.0 to link to right now. I'll fix that.

**Comment by veschup** [comment]
I see. That's the answer to my question. We need the 4.0 link until we have a 5.0 link.  Thanks.

**Comment by dpwspoon** [comment]
@michaelcretzman is this resolved?

**Comment by michaelcretzman** [comment]
No. It isn't. I'll add it to my 5.0/4.0.9 work.

**Comment by michaelcretzman** [comment]
This issue was moved to kaazing/roadmap#619

**Comment by michaelcretzman** [comment]
moved this to Roadmap
