### ISSUE TITLE
Error in NioFileRegionTest

### ISSUE THREAD

**Issue by a-zuckut** [kaazing/gateway#221]
Error in NioFileRegionTest. The logs will be uploaded. 

```
Running org.apache.mina.transport.socket.nio.NioFileRegionTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.041 sec <<< FAILURE!
```

**Comment by krismcqueen** [comment]
[log.txt | uploaded via ZenHub](https://files.zenhub.io/55957c3727ca35b74f68e611)

Logs uploaded

**Comment by dpwspoon** [comment]
Suggestion is to ignore this test as its in mina.core

**Comment by sbadugu** [comment]
We have upgraded NIO Netty.
