### ISSUE TITLE
(doc) Remove reference to GWT

### ISSUE THREAD

**Issue by vjwang** [kaazing/gateway#223]
Remove references to GWT from index.md and any other docs that point to it. See the [story](https://github.com/kaazing/roadmap/issues/401).
 
cc: @chadpowers Please remove GWT from your scripts.

**Comment by michaelcretzman** [comment]
remove from:
- https://github.com/kaazing/gateway/blob/develop/doc/index.md

**Comment by chadpowers** [comment]
@vjwang Done
