### ISSUE TITLE
Update http.keepalive.timeout example to use time unit

### ISSUE THREAD

**Issue by robinzimmermann** [kaazing/gateway#224]
In the [http.keepalive.timeout doc](https://github.com/kaazing/gateway/blob/develop/doc/admin-reference/r_configure_gateway_service.md#httpkeepalivetimeout), the example configuration says:

``` xml
<http.keepalive.timeout>120</http.keepalive.timeout>
```

We should use units for elements with time. This example should say:

``` xml
<http.keepalive.timeout>120 seconds</http.keepalive.timeout>
```

**Comment by veschup** [comment]
This pull request fixes this issue and a few other nits tracked in [#357](https://github.com/kaazing/roadmap/issues/357) for http.proxy.

Pull request: [225](https://github.com/kaazing/gateway/pull/225)

**Comment by vjwang** [comment]
PR reviewed by @robinzimmermann
