### ISSUE TITLE
KGS-976: UP: sporadic error connecting Command Center to JMS 4.0.6 Dev / JMS 4.0.7 Prod

### ISSUE THREAD

**Issue by sbadugu** [kaazing/gateway#226]
<p>E*Trade has been putting our gateway thru its paces and noted the following JavaScript errors propagate to the end-user when a gateway goes down.  We should probably trap these errors and display a more user-friendly message.</p>

<blockquote>
<p>While trying to reproduce the ClassCastException, I get these errors at <a href="http://localhost:8000/commandcenter/html/commandcenter.html#/monitor/sessions" class="external-link" rel="nofollow">http://localhost:8000/commandcenter/html/commandcenter.html#/monitor/sessions</a> when I make a command center request (IE do something on the page) then really quickly kill the gateway (ctrl C)</p>

<p>These are probably "working as intended" errors, for obvious reasons.  But figured would let you know and document them here.</p>

<p>The client (command center javascript) throws these alerts:</p>

<p>Error message: Uncaught Error: SNMP makeSetRequest() on connection <span class="error">&#91;ws://localhost:8000/snmp&#93;</span> that is not OPEN.</p>

<p>URL: <a href="http://localhost:8000/commandcenter/js/general.js" class="external-link" rel="nofollow">http://localhost:8000/commandcenter/js/general.js</a></p>

<p>Line Number: 1389</p>

<p>Error message: Uncaught Error: SNMP makeGetSubtreeRequest() on connection <span class="error">&#91;ws://localhost:8000/snmp&#93;</span> that is not OPEN.</p>

<p>URL: <a href="http://localhost:8000/commandcenter/js/general.js" class="external-link" rel="nofollow">http://localhost:8000/commandcenter/js/general.js</a></p>

<p>Line Number: 1292</p>

<p>Error message: Uncaught Error: SNMP makeGetRequest() on connection <span class="error">&#91;ws://localhost:8000/snmp&#93;</span> that is not OPEN (1), it is 3.</p>

<p>URL: <a href="http://localhost:8000/commandcenter/js/general.js" class="external-link" rel="nofollow">http://localhost:8000/commandcenter/js/general.js</a></p>

<p>Line Number: 1258</p></blockquote>

--------------------------------------------------
Imported from JIRA
Originally reported by: Chad Chervitz
Issue Number: KG-12086

**Comment by sbadugu** [comment]
**jennifer.kirkley** said:
<p>UPRR is getting the below error:</p>

<p>Uncaught error: SNMP makeGetRequest() on connection <span class="error">&#91;ws://node01.sktgwprd01.sgs.apps.uprr.com:8000/snmp&#93;</span> that is not OPEN(1), NOT 2</p>

<p>URL: ws://sktgwprd01.sgs.apps.uprr.com:8000/commandcenter/js/general.js<br/>
Line Number:1258</p>

**Comment by daniel-smith-kaazing** [comment]
Let's hold off on escalating this. New info from UP - this is sporadic and may be related to WSE connection explosion for which we have given them a workaround (KGS-1033/KGS-1038). Let's wait for more feedback from UP before proceeding.

**Comment by sbadugu** [comment]
This issue was moved to kaazing/tickets#67
