### ISSUE TITLE
Remove protocol injection topics again

### ISSUE THREAD

**Issue by vjwang** [kaazing/gateway#228]
Accidentally merged with @chadpowers PR.

https://github.com/kaazing/gateway/blob/develop/doc/security/p_auth_protocol_injection.md
https://github.com/kaazing/gateway/blob/develop/doc/security/p_auth_user_identity_promotion.md

Apply broken link fixes to enterprise.gateway instead.

**Comment by michaelcretzman** [comment]
@vjwang , pull request for this deletion:
https://github.com/kaazing/enterprise.gateway/pull/143

**Comment by michaelcretzman** [comment]
removed the topics from the CE gateway repo:
https://github.com/kaazing/gateway/pull/239
