### ISSUE TITLE
WSN Transport Bug : shouldEchoBinaryFrameWithPayloadLength0 and shouldEchoTextFrameWithPayloadLength0

### ISSUE THREAD

**Issue by chadpowers** [kaazing/gateway#254]
Test shouldEchoBinaryFrameWithPayloadLength0 uses [this K3PO script](https://github.com/k3po/k3po/blob/develop/specification/ws/src/main/scripts/org/kaazing/specification/ws/framing/echo.binary.payload.length.0/handshake.request.and.frame.rpt).

Test shouldEchoTextFrameWithPayloadLength0 uses [this K3PO script](https://github.com/k3po/k3po/blob/develop/specification/ws/src/main/scripts/org/kaazing/specification/ws/framing/echo.text.payload.length.0/handshake.request.and.frame.rpt)

Tests are added in gateway pull #236 

File: BaseFramingIT.java & `@Ignore` has this issue's title.

Error is that script is expecting 'read [0x82 0x00]', actually getting 'Disconnected'. The GATEWAY is not echoing 0 length payload.

**Comment by chadpowers** [comment]
This issue will address many ignores in pull #236, besides just these two. 4 tests in FragmentationIT.java also fail because the gateway throws an exception when echoing an empty payload.

**Comment by cmebarrow** [comment]
Changed bug title from the original "WSN Transport Bug : shouldEchoBinaryFrameWithPayloadLength0 andshouldEchoTextFrameWithPayloadLength0" because we get the same issue with the WSE spec tests (for example: BinaryIT.shouldEchoFrameWithPayloadLength0).

Debugging shows the underlying cause is that the AbstractIoSession.write method so as of IllegalArgumentException if the input data buffer has zero length, i.e. !hasRemaining().

**Comment by danibusu** [comment]
I reproduced the issue. I'm trying to figure out the impact of removing the throw statement from the AbstractIoSession.write method.

**Comment by danibusu** [comment]
@cmebarrow Looking at the gateway project, I can't seem to understand why there's a mina.core module and a mina.build  one. Could you please shed some light?
Also, if I were to change the write() method to no longer throw IllegalArgumentException, I would need to do it in both mina.core and mina,netty, correct?
Thanks!

**Comment by danibusu** [comment]
@cmebarrow I opened this [PR](https://github.com/kaazing/gateway/pull/640), so you can see my changes and discuss whether this is the way to go. The mina modules are used all over the gateway, so I'm not sure of the impact that this change might have. Thanks!

**Comment by cmebarrow** [comment]
@jitsni Jitu, could you take a look at this and answer @danibusu 's questions? I am very busy with BPCE right now. I think his approach is ok except I am not sure about the lowest level (nio/tcp). Allowing a write of a zero length buffer might not make sense for that.
