### ISSUE TITLE
[gateway.transport.wseb]: X-WebSocket-Version header missing in WSE handshake response

### ISSUE THREAD

**Issue by pkhanal** [kaazing/gateway#273]
As per the [WSE Spec](https://github.com/k3po/k3po/blob/develop/specification/wse/SPEC.md#server-handshake-requirements),
`the HTTP handshake response header X-WebSocket-Version MUST have the value wseb-1.0`

However, `X-WebSocket-Version` header is missing in handshake response from gateway.

**NOTE**
I just checked the RFC-6455 spec and found that `Sec-WebSocket-Version` header is not mandatory header in handshake response. May be we need to apply the same approach in WSE Spec.

**Comment by vmaraloiu** [comment]
>NOTE
I just checked the RFC-6455 spec and found that Sec-WebSocket-Version header is not mandatory header in handshake response. May be we need to apply the same approach in WSE Spec.

We should add the missing header in the gateway response or the WSE Spec should be changed?

**Comment by dpwspoon** [comment]
@jfallows thoughts?

**Comment by dpwspoon** [comment]
Not needed
