### ISSUE TITLE
WSN Connector, WSE connector: IllegalArgumentException is thrown when sending a frame with empty payload

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/gateway#306]
When Gateway is acting as a client, trying to send an empty frame(BINARY or TEXT) results in the following exception:
``` java
 java.lang.IllegalArgumentException: message is empty. Forgot to call flip()?
	at org.kaazing.mina.core.session.AbstractIoSession.write(AbstractIoSession.java:436)
	at org.kaazing.mina.core.session.AbstractIoSession.write(AbstractIoSession.java:397)
        ...
```
This can reproduced using the following tests(currently marked @Ignored) in transport/wsn module `org.kaazing.gateway.transport.wsn.specification.ws.connector` package:

0. `BaseFramingIT.shouldEchoBinaryFrameWithPayloadLength0()`
0. `BaseFramingIT.shouldEchoTextFrameWithPayloadLength0()`
0. `FragmentationIT.shouldEchoServerSendBinaryFrameWithEmptyPayloadFragmentedAndInjectedPingPong()`
0. `FragmentationIT.shouldEchoServerSendTextFrameWithEmptyPayloadFragmented()`
0. `FragmentationIT.shouldEchoServerSendTextFrameWithEmptyPayloadFragmentedAndInjectedPingPong()`

This seems to be related to Issue #254 that specifies Acceptor side tests.

**Comment by danibusu** [comment]
This is related to gateway issue #254.

**Comment by danibusu** [comment]
Fixed by [this PR](https://github.com/kaazing/gateway/pull/640)
