### ISSUE TITLE
WSN Connector: Gateway sends back invalid UTF-8 reason instead of just the CLOSE code 1002

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/gateway#307]
When Gateway is acting as a client, if the server sends a CLOSE frame with invalid UTF-8 reason, then Gateway must send back a CLOSE frame with just the status code 1002 as part of the closing handshake. However, the Gateway tries to also send the invalid UTF-8 reason.

This can be reproduced using the `ClosingHandshakeIT.shouldFailWebSocketConnectionWhenServerSendCloseFrameWithCode1000AndInvalidUTF8Reason()` test in transport/wsn module under `org.kaazing.gateway.transport.wsn.specification.ws.connector` package.

**Comment by DoruM** [comment]
Hi,

This bug was solved [here](https://github.com/kaazing/gateway/pull/641).

Best regards,
Doru
