### ISSUE TITLE
WsnConnector does not reject a masked text or binary frame from the server

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/gateway#308]
When Gateway is acting as a client, if the server violates [RFC 6455](https://tools.ietf.org/html/rfc6455) by sending a masked frame(BINARY or TEXT), then Gateway (WsnConnector) just treats the message normally instead of failing the connection, as seen in the following tests under transport/wsn module in  `org.kaazing.gateway.transport.wsn.specification.ws.connector` package:

0. `MaskingIT.shouldFailWebSocketConnectionWhenServerSendsMaskWithTextFrame()`
0. `MaskingIT.shouldFailWebSocketConnectionWhenServerSendsMaskWithBinaryFrame()`

Gateway (i.e. WsnConnector) should instead respond with a CLOSE frame with 1002 code.

**Comment by danibusu** [comment]
Raised [PR](https://github.com/kaazing/gateway/pull/647) with the fix.
