### ISSUE TITLE
WSN Connector: Missing Sec-WebSocket-Extensions header in the handshake request

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/gateway#309]
When Gateway is acting as a client and `ResourceOption` EXTENSIONS is specified while creating the `ResourceAddress` to be able to connect as shown below:

``` java
        Map<String, Object> connectOptions = new HashMap<>();

        if (extensions != null) {
            connectOptions.put(EXTENSIONS.name(), asList(extensions));
        }

        ResourceAddress connectAddress =
                addressFactory.newResourceAddress(URI.create(connect), connectOptions);
        wsnConnector.connect(connectAddress, connectHandler, null);
```

does not result in `Sec-WebSocket-Extensions` header to be included in the handshake request.

This issue can be reproduced in the following tests under transport/wsn module under `org.kaazing.gateway.transport.wsn.specification.ws.connector` package:

0. `OpeningHandshakeIT.shouldEstablishConnectionWithRequestHeaderSecWebSocketExtensions()`
0. `OpeningHandshakeIT.shouldEstablishConnectionWithSomeExtensionsNegotiated()`
0. `OpeningHandshakeIT.shouldEstablishConnectionWhenOrderOfExtensionsNegotiatedChanged()`

**Comment by danibusu** [comment]
@sanjay-saxena @sbadugu I raised to following [PR](https://github.com/k3po/k3po/pull/349) on the k3po repo to modify the scripts related to Sec-WebSocket-Extensions header. Once it is merged and a new version released, I can modify the k3po.version property in the gateway pom.xml and then [this PR](https://github.com/kaazing/gateway/pull/657) can also be merged.

**Comment by danibusu** [comment]
PR was merged, so closing.
