### ISSUE TITLE
WSN Connector: Connection should fail when the value of the `Connection` header in handshake response is not `Upgrade`

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/gateway#310]
When Gateway is acting as a client, if the value of the `Connection` header in the handshake response is different from `Upgrade`, then currently Gateway reports that the connection is successful. However, this violates RFC 6455 and Gateway should terminate the connection if the value of the `Connection` header in the handshake response is not `Upgrade`. For example, `ConnectFuture.isConnected()` should return `false` in the following code:

``` java
ConnectFuture connectFuture = connector.connect("ws://localhost:8080/path?query", null, handler);
connectFuture.awaitUninterruptibly();
assertFalse(connectFuture.isConnected());
```

This can be reproduced using `OpeningHandshakeIT.shouldFailConnectionWhenResponseHeaderConnectionNotUpgrade()` test in transport/wsn module under `org.kaazing.gateway.transport.wsn.specification.ws.connector`package.

**Comment by vmaraloiu** [comment]
@sbadugu This is the [PR](https://github.com/kaazing/gateway/pull/665) with the fix for the issue.
