### ISSUE TITLE
WSN Connector: Missing `Connection` header in handshake response should not result in a successful connection

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/gateway#311]
When Gateway is acting as a client, if the handshake response does not contain the `Connection` header, then Gateway should not report it as a successful connection.  In the following code, `ConnectFuture.isConnected()` returns `true` when the `Connection` header is missing in the handshake response:

``` java
ConnectFuture connectFuture = connector.connect("ws://localhost:8080/path?query", null, handler);
connectFuture.awaitUninterruptibly();
assertFalse(connectFuture.isConnected());
```
This can be reproduced using `OpeningHandshakeIT.shouldFailConnectionWhenResponseHeaderConnectionMissing()` test in transport/wsn module under `org.kaazing.gateway.transport.wsn.specification.ws.connector` package.

**Comment by DoruM** [comment]
Hello,

I have fixed this issue in [this PR](https://github.com/kaazing/gateway/pull/635). There was no check done for the presence of the "Connect" header, when establishing the connection.

Best regards,
Doru

###### Technical notes

According to https://tools.ietf.org/html/rfc6455#section-4.1 : 
>  If the response lacks a |Connection| header field or the |Connection| header field doesn't contain a token that is an ASCII case-insensitive match for the value "Upgrade", the client MUST _Fail the WebSocket Connection_

This check was not done.
