### ISSUE TITLE
WSN Connector: Invalid value for the `Upgrade` header in handshake response must not result in a successful connection

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/gateway#312]
When Gateway is acting as a client, if the the value of the `Upgrade` header in teh handshake response is not `websocket`, then Gateway should not report it as a successful connection.  In the following code, `ConnectFuture.isConnected()` returns `true` when the value of the `Upgrade` header is not `websocket` in the handshake response:

``` java
ConnectFuture connectFuture = connector.connect("ws://localhost:8080/path?query", null, handler);
connectFuture.awaitUninterruptibly();
assertFalse(connectFuture.isConnected());
```

`ConnectFuture.isConnected()` must return false in this scenario. This can be reproduced using `OpeningHandshakeIT.shouldFailConnectionWhenResponseHeaderUpgradeNotWebSocket()` test in transport/wsn module under `org.kaazing.gateway.transport.wsn.specification.ws.connector` package.

**Comment by DoruM** [comment]
This issue was fixed by @jitsni. The fix was done in [this commit](https://github.com/kaazing/gateway/commit/c61f093d44051cf0f7441191f55092d53ede5b2b)

The unit test was however not un-suspended. I have created a new [PR](https://github.com/kaazing/gateway/pull/642) containing this change.
