### ISSUE TITLE
WSN Connector: Connection should fail when the negotiated extension is not in the list of supported extensions

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/gateway#314]
When Gateway is acting as a client, if the negotiated extension in handshake response does not match any of the extensions in the list of supported extensions that were included in the handshake request, then the connection must fail.

This can be reproduced using `OpeningHandshakeIT.shouldFailConnectionWhenResponseHeaderSecWebSocketExtensionsNotNegotiated()` test in transport/wsn module under `org.kaazing.gateway.transport.wsn.specification.ws.connector` package.

**Comment by danibusu** [comment]
Changes required for this issue are included in [this PR](https://github.com/kaazing/gateway/pull/657).

**Comment by danibusu** [comment]
Fixed by [this PR](https://github.com/kaazing/gateway/pull/640).

**Comment by danibusu** [comment]
PR was merged, so closing.
