### ISSUE TITLE
Wse Acceptor: should not connect if "X-Accept-Commands" has wrong values

### ISSUE THREAD

**Issue by chao-sun-kaazing** [kaazing/gateway#322]
Wse spec K3po test failed.
file:
gateway.transport.wseb/src/test/java/org/kaazing/gateway/transport/wse/specification/ws/acceptor/OpeningHandshakeIT.java
test:
requestHeaderAcceptCommandsNotPing()

**Comment by dpwspoon** [comment]
@chao-sun-kaazing, if possible please attach logs to the bugs.

**Comment by cmebarrow** [comment]
Fixed in PR https://github.com/kaazing/gateway/pull/418
