### ISSUE TITLE
Wse Acceptor: should not connect if "X-Sequence-Number" is missing or has wrong values

### ISSUE THREAD

**Issue by chao-sun-kaazing** [kaazing/gateway#323]
k3po spec test failed
file:
gateway.transport.wseb/src/test/java/org/kaazing/gateway/transport/wse/specification/ws/acceptor/OpeningHandshakeIT.java
tests:
1. requestHeaderSequenceNumberMissing()
2. requestHeaderSequenceNumberNegative()
3. requestHeaderSequenceNumberNotInteger()
4. requestHeaderSequenceNumberOutOfRange()

**Comment by cmebarrow** [comment]
Fixed in PR https://github.com/kaazing/gateway/pull/418
