### ISSUE TITLE
Wse Acceptor: Missing HTTP header: X-WebSocket-Extensions in respose

### ISSUE THREAD

**Issue by chao-sun-kaazing** [kaazing/gateway#324]
wse spec k3po test fail.
file
/gateway.transport.wseb/src/test/java/org/kaazing/gateway/transport/wse/specification/ws/acceptor/OpeningHandshakeIT.java
test
requestHeaderWebSocketExtensions()

**Comment by cmebarrow** [comment]
Fixed in PR https://github.com/kaazing/gateway/pull/418
