### ISSUE TITLE
Wse Acceptor: Missing HTTP header: X-WebSocket-Protocol in response

### ISSUE THREAD

**Issue by chao-sun-kaazing** [kaazing/gateway#325]
Wse k3po spec test failed
file:
gateway.transport.wseb/src/test/java/org/kaazing/gateway/transport/wse/specification/ws/acceptor/OpeningHandshakeIT.java
test:
requestHeaderWebSocketProtocol()

**Comment by cmebarrow** [comment]
Fixed in PR https://github.com/kaazing/gateway/pull/418
