### ISSUE TITLE
Wse Acceptor: should not connect if method is not Post

### ISSUE THREAD

**Issue by chao-sun-kaazing** [kaazing/gateway#327]
wse k3po spec test failed:
file
gateway.transport.wseb/src/test/java/org/kaazing/gateway/transport/wse/specification/ws/acceptor/OpeningHandshakeIT.java
test:
requestMethodNotPost()

**Comment by cmebarrow** [comment]
Fixed in PR https://github.com/kaazing/gateway/pull/418
