### ISSUE TITLE
gateway.bridge.jar does not contain both JS and Java bridge

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/gateway#337]
Currently, gateway.bridge.jar does not seem to contain JS and Java bridges. Also, it looks like repo `kaazing-client-javascript-bridge` was moved under `javascript.client`. AFAIK, the client repos will not be released going forward. If that is the case, it's not clear how Gateway will pick up and package the JS bridge in gateway.bridge.jar.

BTW, JS bridge depends on JS Util(aka `gateway.client.javascript.util` / `kaazing-client-javascript-util`) which has also been consolidated under `javascript.client`.

**Comment by dpwspoon** [comment]
I would recommending creating a enterprise.gateway bridge jar in kaazing/enterprise.gateway that consumes and the community bridge jar and adds the 4.x client bridges.  Looks like the gateway.bridge module in kaazing/gateway is broken, as it should still pull in 5.x client bridges that have been released.  Would that work?

**Comment by sanjay-saxena** [comment]
Maybe. The code that deals with populating the `GATEWAY_HOME/temp` with the bridge is in CE.

I would think that the same bridge would work for both 4.x and 5.x clients. If that is the case, then there wouldn't be any need for separate bridges for CE and EE.

**Comment by dpwspoon** [comment]
closing as dup of https://github.com/kaazing/tickets/issues/237
