### ISSUE TITLE
WSE: Query parameters not available on upstream/downstream URLs

### ISSUE THREAD

**Issue by krismcqueen** [kaazing/gateway#36]
**Client Technology**  K3PO

**Browser with Version**  n/a

**Client O/S with Version**  n/a

**Gateway with version**  5.3.0.1-SNAPSHOT (current develop branch of Gateway)

**Gateway Java version**  1.8.0_31

**Server OS with version:**  Ubuntu 14.04

**Back-End System with version** n/a

**Can the bug be reproduced in a Kaazing demo out-of-the-box?** 

**Does the bug reproduce with all emulated or native combinations?** emulated (it's a WSE robot test)

**Is this a regression from previous released version?** no

**Steps to reproduce:** Run the robot test https://github.com/kaazing/gateway/blob/develop/gateway.transport.wseb/src/test/java/org/kaazing/gateway/transport/wseb/WsebTransportIT.java, specifically shouldPropagateQueryParametersFromCreateToUpstreamAndDownstream() with some modifications (detailed in a later comment) to the rupert script

**Observed behavior:** test fails due to query parameters not propogated to upstream/downstream URLs

**Expected behavior:** the test should succeed because query parameters are correctly observed on upstream/downstream URLs

This appears to be an issue where the query string is not correctly reported to WSEB from the HTTP layer.  When just a path is used for the GET request, the test works as expected.  When the absolute URL is used as indicated in the client code the test does not work.

**Comment by krismcqueen** [comment]
I had originally tried to put the example request that should get sent (the robot script currently uses an origin-form with just the path "/echo/;e/ct?param=value").  The request is as follows:

GET http://localhost:8000/echo/;e/ct?param=value HTTP/1.1
Host: localhost:8000
X-Origin: http://localhost:8000
X-WebSocket-Version: wseb-1.0

One way to generate this request it to use raw TCP and write the HTTP directly over TCP.  Another way might be to use the

write request "absolute-form"

directive in the rupert script.

**Comment by dpwspoon** [comment]
This fails with absolute form, which is a bug.  But the test is currently enabled and running fine using origin form.

**Comment by sbadugu** [comment]
This would only affect forward proxies and gateway cannot be used as a forward proxy.
