### ISSUE TITLE
Need better diagnostics when a ProtocolDecoderException occurs or other unexpected transport exception

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#384]
If for example a WebSocket protocol error is detected, the WebSocket connection is closed, but unless log level is set to debug or finer, the only message in the Gateway log file indicating there was an issue is the generic "java.io.IOException: Early termination of IO session", which gives no indication of the underlying cause. We should include the underlying cause in this message when there is one.

To reproduce:
Run any of the failure scenario tests in org.kaazing.gateway.transport.wsn.specification.ws.connector.FragmentationIT, for example, shouldFailWebSocketConnectionWhenServerSendBinaryFrameWithPayloadFragmentedButNotContinued, after tweaking the test to print out log messages (simplest way is to force test failure by adding the line "throw new Exception();" at the end of the test method. This causes trace level of messages to be printed out. But by examining only the INFO level messages one can see that the only one indicating it was an issue is

```
540  transport.wsn.connect [New I/O worker #1] INFO  connect  - [wsn#3 /127.0.0.1:56462] EXCEPTION: java.io.IOException: Early termination of IO session
```

which does not indicate the cause of the problem (which was 

``` if
ProtocolDecoderException: Expecting CONTINUATION frame, but got BINARY frame 
```

)

The full trace level log output from running the above test is available at:
[issue_384_out.txt](https://files.zenhub.io/56943160d4ec3c2c3bf4a1b5)
It is easy to see from this, by scanning for "ProtocolDecoderException", that the only log messages mentioning that exception are DEBUG or TRACE level (exception stack traces are always part of the preceding log message).

**Comment by cmebarrow** [comment]
I would suggest we add a cause exception in these cases to the IOException that we throw, and enhance LoggingFilter to into the cause exception in the EXCEPTION message when available

**Comment by cmebarrow** [comment]
This was fixed by PR https://github.com/kaazing/gateway/pull/396

**Comment by Archish27** [comment]
@cmebarrow Can you please guide how logging level was increased?
