### ISSUE TITLE
http transport is not parsing certain comma separated http headers correctly (ones used for wseb)

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#410]
Notable examples are X-WebSocket-Protocol and X-WebSocket-Extensions. This causes two wseb acceptor specification tests to fail in OpeningIT: shouldEstablishConnectionWithRequestHeaderXWebSocketProtocol and shouldEstablishConnectionWithRequestHeaderXWebSocketExtensions

**Comment by jfallows** [comment]
As discussed, by default HTTP headers are single-valued, and only known multi-valued headers can have comma-separated values, or be multiply specified as separate headers.

There are well-defined standard multi-valued headers, and some of our custom wse headers are also multi-valued, as indicated here.

**Comment by cmebarrow** [comment]
Fixed by PR https://github.com/kaazing/gateway/pull/411
