### ISSUE TITLE
wsn transport is reacting incorrectly to case where maximum ws message size is exceeded

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#463]
As @Anisotrop remarked in comments in https://github.com/kaazing/gateway/pull/445, the server (wsn transport) continues to read incoming data after detecting that the incoming WebSocket frame size exceeds the configured limit. This results in further protocol decoder errors and is also in violation of RFC 6455, which states (in section [7.1.7 Fail the WebSocket connection](http://tools.ietf.org/html/rfc6455#section-7.1.7)
```
An endpoint MUST NOT continue to attempt to
   process data (including a responding Close frame) from the remote
   endpoint after being instructed to _Fail the WebSocket Connection_.
```
and section [10.4.  Implementation-Specific Limits](http://tools.ietf.org/html/rfc6455#section-10.4) implies that when the limit is exceeded the server should fail the WebSocket connection.

To reproduce:
- Alter test LimitsMaxSizeDefaultIT by adding a throw instruction as follows:
```
    public void shouldRefuseBinaryFrameWithPayloadLengthExceeding128KiB() throws Exception {
        k3po.finish();
        throw new Exception("TEMP");
    }
```
- Run the test from Eclipse, or the command line: 
`mvn verify -DskipTests  -Dit.test=LimitsMaxSizeDefaultIT `
The throw causes trace level of messages to be printed out (thanks to the MethodExecutionTrace rule). These show numerous protocol decoder exceptions after the detection of the message size exceeded exception, indicating that the server is continuing to read incoming data in violation of the spec.

**Comment by sbadugu** [comment]
@cmebarrow It seems like you already have the fix for this bug based on your [comment](https://github.com/kaazing/gateway/pull/445#issuecomment-199603427). You can post the PR here and close this issue, when you are back :)

**Comment by cmebarrow** [comment]
Fix is in my branch gateway_issue_463

**Comment by cmebarrow** [comment]
This was fixed by PR https://github.com/kaazing/gateway/pull/466 which was merged on 28-Mar-16
