### ISSUE TITLE
Integration tests failing in HTTP directory service

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#47]
3 IT's are failing in service.http.directory on Windows 7
- HttpDirectoryServiceIT.testGetIndexCheckWholeResponse (unexpected content-length header value)
- HttpDirectoryServiceIT.testHexEncodedUri (ditto)
- HttpPipeliningIT.twoRequestsBeforeReponseOK (unexpected Data header value?)

**Comment by dpwspoon** [comment]
Are these consistent, and are they failing on Windows.  I can't reproduced on my mac??

**Comment by cmebarrow** [comment]
HttpPipeliningIT failure does not reproduce when the test is run alone (from eclipse or the command line).

**Comment by cmebarrow** [comment]
Fixed in pull request #45

**Comment by cmebarrow** [comment]
Closed by accident, re-opened

**Comment by cmebarrow** [comment]
Fixed by pull request #48
