### ISSUE TITLE
Extension filter is not removed when WSEB's TransportSession is closed

### ISSUE THREAD

**Issue by jitsni** [kaazing/gateway#555]
Extension filter's IoFilter#onPostRemove() is not invoked. Revalidate filter uses this method to unbind revalidate addresses.

**Comment by sbadugu** [comment]
Issue moved to [kaazing/tickets #471](https://github.com/kaazing/tickets/issues/471) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by jitsni** [comment]
PR https://github.com/kaazing/gateway/pull/556
