### ISSUE TITLE
Occasional build failure in wseb acceptor spec test ControlIT.shouldCloseConnectionOnReceivingInvalidPingFromClient

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#580]
This failure occurred for example in build #1540 on Travis. Here's an extract from the build output showing the failure:
```
shouldCloseConnectionOnReceivingInvalidPingFromClient(org.kaazing.gateway.transport.wseb.specification.wse.acceptor.ControlIT)  Time elapsed: 0.147 sec  <<< FAILURE!
org.junit.ComparisonFailure: Specified behavior did not match expected:<...close

read status "[200" /.+/
read header "Content-Type" "application/octet-stream"
read header "Connection" "close"

read [0x01 0x30 0x32 0xFF]
read [0x01 0x30 0x31 0xFF]
read closed]

# Upstream
connect...> but was:<...close

read status "[404"]
```
Looking at the specification script: [client.send.invalid.ping/request.rpt](https://github.com/k3po/k3po/blob/develop/specification/wse/src/main/scripts/org/kaazing/specification/wse/control/client.send.invalid.ping/request.rpt), it is clear this is an issue with the script. There is a race between the establishment of the upstream and the sending of the invalid ping frame and the establishment of the downstream. If the downstream connects after the upstream then the observed behavior is correct (status 404 response, not found, on the downstream, because the logical wseb connection was already closed). This needs to be fixed in the spec scripts: use barriers to force downstream to be established before the invalid ping frame is sent on the upstream. If have filed k3po issue https://github.com/k3po/k3po/issues/339 for this.

**Comment by jitsni** [comment]
k3po PR https://github.com/k3po/k3po/pull/369
