### ISSUE TITLE
Issue with finer to coarser granularity conversion of time unit in config file 

### ISSUE THREAD

**Issue by jitsni** [kaazing/gateway#595]
When converting time from finer to coarser granularities truncate as the code uses TimeUnit#convert().

For example, if the config specifies http.keepalive.timeout as 60000ms, it is reflected as 0 instead of 60s.

**Comment by vmaraloiu** [comment]
@sbadugu Here is the [PR](https://github.com/kaazing/gateway/pull/649) with the changes added so far, in order to fix the time conversion issue. It should not be merged yet, I am still testing it.

**Comment by vmaraloiu** [comment]
The PR in the previous comment can be merged.
