### ISSUE TITLE
AcceptUriComparedToBalanceUriVisitor is comparing URIs prior to parameters being replaced, causing NPE that throws Parse Exception

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/gateway#612]
This config throws an NPE

```
    <properties>
        <property>
            <name>balance.node1.accept</name>
            <value>http://localhost:8010/jms</value>
        </property>
        <property>
            <name>node1.accept</name>
            <value>http://localhost:8011/jms</value>
        </property>
        <property>
            <name>node1.cluster</name>
            <value>tcp://127.0.0.1:61616</value>
        </property>
        <property>
            <name>node2.cluster</name>
            <value>tcp://127.0.0.1:61617</value>
        </property>
    </properties>

    <cluster>
       <name>MyCluster</name>
       <accept>tcp://127.0.0.1:61616</accept>
       <connect>tcp://127.0.0.1:61617</connect>
    </cluster>
    
    <service>
       <name>Balancer</name>
       <accept>${balancer.node1.accept}</accept>
       <type>balancer</type>
       <accept-options>
           <ws.bind>tcp://127.0.0.1:8010</ws.bind>
       </accept-options>
       <cross-site-constraint>
           <allow-origin>*</allow-origin>
       </cross-site-constraint>
    </service>

    <!-- JMS service: using external JMS provider (ActiveMQ) -->
    <service>
        <name>jms service</name>
        <accept>${node1.accept}</accept>
        <balance>${balancer.node1.accept}</balance>
        <type>jms</type>
        <properties>
            <connection.factory.name>ConnectionFactory
            </connection.factory.name>
            <context.lookup.topic.format>dynamicTopics/%s
            </context.lookup.topic.format>
            <context.lookup.queue.format>dynamicQueues/%s
            </context.lookup.queue.format>
            <env.java.naming.factory.initial>org.apache.activemq.jndi.ActiveMQInitialContextFactory
            </env.java.naming.factory.initial>
            <env.java.naming.provider.url>${broker.url}
            </env.java.naming.provider.url>
        </properties>
        <cross-site-constraint>
            <allow-origin>*</allow-origin>
        </cross-site-constraint>
    </service>
```

output from 1:
>
org.kaazing.gateway.server.config.parse.GatewayConfigParserException
	at org.kaazing.gateway.server.config.parse.GatewayConfigParser.parse(GatewayConfigParser.java:219)
	at org.kaazing.gateway.server.impl.GatewayImpl.launch(GatewayImpl.java:302)
	at org.kaazing.gateway.server.GatewayCommandLineProcessor.launchGateway(GatewayCommandLineProcessor.java:100)
	at org.kaazing.gateway.server.GatewayCommandLineProcessor.launchGateway(GatewayCommandLineProcessor.java:45)
	at org.kaazing.gateway.server.Main.main(Main.java:37)

This config throws proper exception

```
<gateway-config xmlns="http://xmlns.kaazing.org/2015/11/gateway">
    <properties>
        <property>
            <name>balance.node1.accept</name>
            <value>http://localhost:8010/jms</value>
        </property>
        <property>
            <name>node1.accept</name>
            <value>http://localhost:8011/jms</value>
        </property>
        <property>
            <name>node1.cluster</name>
            <value>tcp://127.0.0.1:61616</value>
        </property>
        <property>
            <name>node2.cluster</name>
            <value>tcp://127.0.0.1:61617</value>
        </property>
    </properties>

    <cluster>
       <name>MyCluster</name>
       <accept>tcp://127.0.0.1:61616</accept>
       <connect>tcp://127.0.0.1:61617</connect>
    </cluster>
    
    <service>
       <name>Balancer</name>
       <accept>http://localhost:8010/jms</accept>
       <type>balancer</type>
       <accept-options>
           <ws.bind>tcp://127.0.0.1:8010</ws.bind>
       </accept-options>
       <cross-site-constraint>
           <allow-origin>*</allow-origin>
       </cross-site-constraint>
    </service>

    <!-- JMS service: using external JMS provider (ActiveMQ) -->
    <service>
        <name>jms service</name>
        <accept>http://localhost:8011/jms</accept>
        <balance>http://localhost:8010/jms</balance>
        <type>jms</type>
        <properties>
            <connection.factory.name>ConnectionFactory
            </connection.factory.name>
            <context.lookup.topic.format>dynamicTopics/%s
            </context.lookup.topic.format>
            <context.lookup.queue.format>dynamicQueues/%s
            </context.lookup.queue.format>
            <env.java.naming.factory.initial>org.apache.activemq.jndi.ActiveMQInitialContextFactory
            </env.java.naming.factory.initial>
            <env.java.naming.provider.url>${broker.url}
            </env.java.naming.provider.url>
        </properties>
        <cross-site-constraint>
            <allow-origin>*</allow-origin>
        </cross-site-constraint>
    </service>
```

output from 2
>
org.kaazing.gateway.server.config.parse.GatewayConfigParserException: Accept URI: http://localhost:8011/jms does not match balance URI http://localhost:8010/jms in all but hostname.  Unable to launch Gateway.
	at org.kaazing.gateway.server.config.parse.GatewayConfigParser.parse(GatewayConfigParser.java:219)
	at org.kaazing.gateway.server.impl.GatewayImpl.launch(GatewayImpl.java:302)
	at org.kaazing.gateway.server.GatewayCommandLineProcessor.launchGateway(GatewayCommandLineProcessor.java:100)
	at org.kaazing.gateway.server.GatewayCommandLineProcessor.launchGateway(GatewayCommandLineProcessor.java:45)
	at org.kaazing.gateway.server.Main.main(Main.java:37)

**Comment by DoruM** [comment]
Hi David,

There are a couple of problems. 

## No NPE in head of develop branch
This issue is reproducible with the version on the website, but not with the latest version of the gateway, on "develop" branch.

This is how it looks like:

INFO  Configuration file: D:\Kaazing\kaazing-gateway-community-5.1.0\conf\gatewa
y-config.xml
ERROR Validation errors in gateway configuration file
ERROR Validation errors in gateway configuration file
ERROR   Could not determine non-null value for parameter definition ${balancer.node1.accept}
ERROR   Could not determine non-null value for parameter definition ${balancer.node1.accept}
ERROR   Could not determine non-null value for parameter definition ${balancer.node1.accept}
ERROR   Could not determine non-null value for parameter definition ${balancer.node1.accept}
ERROR   Could not determine non-null value for parameter definition ${broker.url}
ERROR   Could not determine non-null value for parameter definition ${broker.url}
ERROR Gateway failed to launch
org.kaazing.gateway.server.config.parse.GatewayConfigParserException: Validation errors in gateway configuration file
        at org.kaazing.gateway.server.config.parse.GatewayConfigParser.validateGatewayConfig(GatewayConfigParser.java:409)
        at org.kaazing.gateway.server.config.parse.GatewayConfigParser.parse(GatewayConfigParser.java:307)
        at org.kaazing.gateway.server.impl.GatewayImpl.launch(GatewayImpl.java:302)
        at org.kaazing.gateway.server.GatewayCommandLineProcessor.launchGateway(GatewayCommandLineProcessor.java:100)
        at org.kaazing.gateway.server.GatewayCommandLineProcessor.launchGateway(GatewayCommandLineProcessor.java:45)
        at org.kaazing.gateway.server.WindowsMain.main(WindowsMain.java:59)
org.kaazing.gateway.server.config.parse.GatewayConfigParserException: Validation errors in gateway configuration file
        at org.kaazing.gateway.server.config.parse.GatewayConfigParser.validateGatewayConfig(GatewayConfigParser.java:409)
        at org.kaazing.gateway.server.config.parse.GatewayConfigParser.parse(GatewayConfigParser.java:307)
        at org.kaazing.gateway.server.impl.GatewayImpl.launch(GatewayImpl.java:302)
        at org.kaazing.gateway.server.GatewayCommandLineProcessor.launchGateway(GatewayCommandLineProcessor.java:100)
        at org.kaazing.gateway.server.GatewayCommandLineProcessor.launchGateway(GatewayCommandLineProcessor.java:45)
        at org.kaazing.gateway.server.WindowsMain.main(WindowsMain.java:59)


## "Correct" Sample configuration is incorrect
What you are mentioning as "proper exception" is not proper (since "broker.url" is not defined).

## Error hiding anti-pattern
I have noticed in the code for the parsing of Gateway configurations, a lot of lines like this:

>throw new Exception("........");

This causes issues later down the line, because we are forced to use "catch (Exception ex)" and so on .

I believe this should be fixed, but I need some confirmation.

For this purposes please look at:

line 80 in GatewayConfigTranslatorFactory.java
line 179 and 181 in GatewayConfigParser.java

**Comment by dpwspoon** [comment]
Thanks @DoruM for finding my mistake.  Agree in the Exception anti pattern.  Feel free to fix 

For some background on the state of configuration.  Currently the gateway has the following code paths to starting:

1) XML -->  XMLBeans parsing (translators here in loop) --> XMLBeans Objects --> ContextResolvers --> Context --> Gateway and Service Starts

and

2) ConfigurationBuilder --> ConfigurationObjects --> XMLBeansObjects  --> ContextResolvers --> Context --> Gateway and Service Starts

XML beans is old and no longer actively supported, and if forces us to go down a bunch of paths we don't want to go down (like enforcing strict ordering of config elements).

Furthermore, the two code paths have issues as error checking should be done in both paths prior to an error.

The long term plan which we have never completed was to go to this path

XML --> Stax (or sometype) parser driving ConfigurationBuilder --> ConfigurationObjects --> Gateway and service starts

**Comment by dpwspoon** [comment]
Closing due to my mistake
