### ISSUE TITLE
Simplify http.balancer.service configuration

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/gateway#614]
The balancer config parsing currently enforces that every thing in the accept and connect url hostname of the accept and balance url.  However, the default behavior of the client redirect policy is to not load balance on different hostnames.

This enforcement was done because in the future we want load balancing to point to a direct url, i.e. gateway.example.com. And then individual nodes will be balanced via a prefix domain, such as node1.gateway.example.com.

Due to the issue in paragraph one we should remove the check and allow configuration of the balancer service has done in the past.  This should be a high priority story.

Next, we should add a feature to configure load balancing in the service directly.  More details to come in story, but high level is that this will deprecate the balancer service config.  Instead balancing will be implicit with an http accept options such as `http.node.url` (name to change, ping @robinzimmermann for link to design doc or better name).  That http.node.url will need to be the hostname that the service will directly reference.  I.E `node1.gateway.example.com` in the example above.  This new implementation would ideally, not use the balancer service.

The doc should deprecate the old way.

**Comment by sbadugu** [comment]
Make sure that the design for this will fix the following [bug](https://github.com/kaazing/tickets/issues/314)

**Comment by dpwspoon** [comment]
This issue will no longer be solved. closing for now
