### ISSUE TITLE
Remove all but hostname must match gateway-config.xml balancer check

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/gateway#615]

**Comment by msalavastru** [comment]
@dpwspoon I have been looking over the [ecpic](https://github.com/kaazing/gateway/issues/614) of this issue, but it is not fully clear to me what needs to be done. Can you please provide some more detail on this issue, maybe even some config examples, if you think they would further clear the understanding of the requirements? 

I think there is some missing information from the following paragraphs to make them fully understandable:

> The balancer config parsing currently enforces that every thing in the accept and connect url hostname of the accept and balance url.

> Due to the issue in paragraph one we should remove the check and allow configuration of the balancer service has done in the past.

**Comment by msalavastru** [comment]
@sbadugu @dpwspoon Do you have any updates on my comment above? This is blocking me to start working on this issue.

**Comment by dpwspoon** [comment]
[This class](https://github.com/kaazing/gateway/blob/develop/server/src/main/java/org/kaazing/gateway/server/config/parse/translate/sep2014/AcceptUriComparedToBalanceUriVisitor.java) has the checks that should be removed.  It should be pretty easy to just remove that class, references, and tests

**Comment by msalavastru** [comment]
@sbadugu This is the [PR](https://github.com/kaazing/gateway/pull/623) for this issue.

**Comment by dpwspoon** [comment]
There are changes needed in EE gateway (specifically tests that are no longer needed because of this change).   For example ConfigEnforcementTest#testInvalidWSandWSS and others.

**Comment by sbadugu** [comment]
@msalavastru 
There's a [PR](https://github.com/kaazing/enterprise.gateway/pull/386) for EE changes made by @justinma246 .

Once the Gateway is released the PR will be merged and this issue will be closed. So, there is no action item on you, yet. But this will be kept open until we merge the PR for EE.
