### ISSUE TITLE
Tech Debt:  Figure out internal API of nested properties with same name

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/gateway#677]
This comes from a TODO from https://github.com/kaazing/gateway/pull/674/files#r74139669

**Comment by sanjay-saxena** [comment]
Maybe, I am not understanding this but I believe nested properties support was already added with this [pull-request](https://github.com/kaazing/gateway/pull/607).

**Comment by dpwspoon** [comment]
Thanks Sanjay.  After reviewing the PR it looks like the original implementation did not work for properties with the same key.  In xml this would be 

```xml
  <uris>
    <uri>one</uri>
    <uri>two</uri>
    <uri>three</uri>
  <uris>
```
Or in builder terms this would be 

```java
                            .nestedProperty("uris")
                                .property("uri", "uri1")
                                .property("uri", "uri2")
                                .property("uri", "uri3")
                            .done()
```

The implementation in the builder was clearing out all but the last value in the map.  In the originally linked PR (kaazing/gateway#674) The Builder on Config api was fixed to support this use case.  But the representation on the GatewayContext objects was hacked around with an inserted comma.  This ticked is to fix the GatewayContext object representation of that.

I hope that the build change did not break any uses in the EE GW (do you know of any place it might of).

**Comment by dpwspoon** [comment]
Closing as Wont fix
