### ISSUE TITLE
Sslv3Test#connectSucceedsWithoutSslv3 fails intermittently

### ISSUE THREAD

**Issue by jitsni** [kaazing/gateway#71]
Pasting the relevant log from https://s3.amazonaws.com/archive.travis-ci.org/jobs/55579443/log.txt

It also appears that tests are running in parallel as you can see in the following log.
---------------------------
2448 [Time-limited test] DEBUG transport.tcp.accept  - TCP acceptor: worker count = 32
2639 [Time-limited test] INFO org.kaazing.gateway.transport.nio.AbstractNioAcceptor  - Bound to resource: tcp://127.0.0.1:9557
2641 [Time-limited test] INFO org.kaazing.gateway.transport.nio.AbstractNioAcceptor  - Bound to resource: tcp://[0:0:0:0:0:0:0:1]:9557
2824 [Time-limited test] INFO org.kaazing.gateway.transport.nio.AbstractNioAcceptor  - Bound to resource: tcp://127.0.0.1:9558
2826 [Time-limited test] INFO org.kaazing.gateway.transport.nio.AbstractNioAcceptor  - Bound to resource: tcp://[0:0:0:0:0:0:0:1]:9558
2826 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Starting server
2826 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Starting services
2827 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  -   ssl://localhost:9558
2827 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  -   tcp://localhost:9557
2827 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Started services
2845 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Started server successfully in 2.765 secs at 2015-03-24 15:34:07
2850 [New I/O server boss #33] DEBUG transport.tcp.accept  - nextWorker: returning worker #1 of 32
2947 [New I/O worker #1] DEBUG org.kaazing.gateway.service.proxy.AbstractProxyHandler  - [1] session created ((#00000001: kaazing niosocketchannel, server, /127.0.0.1:53681 => /127.0.0.1:9557))
2949 [New I/O worker #1] DEBUG transport.tcp.accept  - [tcp#1] OPENED: (#00000001: kaazing niosocketchannel, server, /127.0.0.1:53681 => /127.0.0.1:9557)
2999 [New I/O worker #1] DEBUG transport.tcp.connect  - TCP connector: worker count = 32
3037 [New I/O server boss #33] DEBUG transport.tcp.accept  - nextWorker: returning worker #2 of 32
3092 [New I/O worker #1] DEBUG transport.tcp.connect  - [tcp#3] OPENED: (#00000003: kaazing niosocketchannel, client, /127.0.0.1:41603 => /127.0.0.1:9558)
3109 [New I/O worker #2] DEBUG transport.ssl.accept  - [ssl#2] OPENED: (#00000002: kaazing niosocketchannel, server, /127.0.0.1:41603 => /127.0.0.1:9558)
3109 [New I/O worker #2] DEBUG transport.tcp.accept  - [tcp#2] OPENED: (#00000002: kaazing niosocketchannel, server, /127.0.0.1:41603 => /127.0.0.1:9558)
3344 [New I/O worker #2] DEBUG org.kaazing.mina.filter.codec.ProtocolCodecFilter  - Processing a MESSAGE_RECEIVED for session 2
3455 [New I/O worker #2] DEBUG performance.tcp  - AbstractNioWorker.process(Selector) took 118 ms: 1 reads, 0 writes
3608 [New I/O worker #1] DEBUG performance.tcp  - AbstractNioWorker.process(Selector) took 152 ms: 1 reads, 0 writes
3708 [New I/O worker #2] DEBUG performance.tcp  - AbstractNioWorker.process(Selector) took 100 ms: 1 reads, 0 writes
3713 [New I/O worker #2] DEBUG transport.ssl.accept  - SSL session ID [B@61beb1cd on transport session #2 (#00000002: kaazing niosocketchannel, server, /127.0.0.1:41603 => /127.0.0.1:9558): cipher TLS_RSA_WITH_AES_256_CBC_SHA256, app buffer size 16916, packet buffer size 16921
3714 [New I/O worker #2] DEBUG transport.ssl.accept  - SSL session ID [B@2e8b3bdd on transport session #2 (#00000002: kaazing niosocketchannel, server, /127.0.0.1:41603 => /127.0.0.1:9558): cipher TLS_RSA_WITH_AES_256_CBC_SHA256, app buffer size 16916, packet buffer size 16921
3718 [New I/O worker #1] DEBUG transport.ssl.connect  - SSL session ID [B@3d80babf on transport session #3 (#00000003: kaazing niosocketchannel, client, /127.0.0.1:41603 => /127.0.0.1:9558): cipher TLS_RSA_WITH_AES_256_CBC_SHA256, app buffer size 16916, packet buffer size 16921
3986 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for one.example.test (alias: one.example.test)
3986 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for www.one.example.test (alias: one.example.test)
3987 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for two.example.test (alias: two.example.test)
3987 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for www.two.example.test (alias: two.example.test)
3987 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for one.kaazing.test (alias: one.kaazing.test)
3987 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for www.one.kaazing.test (alias: one.kaazing.test)
3988 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for two.kaazing.test (alias: two.kaazing.test)
3988 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for www.two.kaazing.test (alias: two.kaazing.test)
3988 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for *.kaazing.test (alias: .kaazing.test)
3988 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for kaazing.test (alias: .kaazing.test)
3989 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for localhost (alias: localhost)
3989 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for www.localhost (alias: localhost)
3991 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for one.example.test (alias: one.example.test)
3991 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for www.one.example.test (alias: one.example.test)
3991 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for two.example.test (alias: two.example.test)
3992 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for www.two.example.test (alias: two.example.test)
3992 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for one.kaazing.test (alias: one.kaazing.test)
3992 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for www.one.kaazing.test (alias: one.kaazing.test)
3992 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for two.kaazing.test (alias: two.kaazing.test)
3993 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for www.two.kaazing.test (alias: two.kaazing.test)
3993 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for *.kaazing.test (alias: .kaazing.test)
3993 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for kaazing.test (alias: .kaazing.test)
3993 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for localhost (alias: localhost)
3994 [Time-limited test] DEBUG org.kaazing.gateway.transport.ssl.cert.VirtualHostKeySelector  - Found certificate for www.localhost (alias: localhost)
4061 [Time-limited test] DEBUG transport.tcp.accept  - TCP acceptor: worker count = 32
4082 [Time-limited test] INFO org.kaazing.gateway.transport.nio.AbstractNioAcceptor  - Bound to resource: tcp://127.0.0.1:8555
4083 [Time-limited test] INFO org.kaazing.gateway.transport.nio.AbstractNioAcceptor  - Bound to resource: tcp://[0:0:0:0:0:0:0:1]:8555
4083 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Starting server
4083 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Starting services
4084 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  -   ssl://localhost:8555
4084 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Started services
4084 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Started server successfully in 0.085 secs at 2015-03-24 15:34:11
4098 [New I/O server boss #67] DEBUG transport.tcp.accept  - nextWorker: returning worker #1 of 32
4113 [New I/O worker #35] DEBUG transport.ssl.accept  - [ssl#4] OPENED: (#00000004: kaazing niosocketchannel, server, /127.0.0.1:43120 => /127.0.0.1:8555)
4114 [New I/O worker #35] DEBUG transport.tcp.accept  - [tcp#4] OPENED: (#00000004: kaazing niosocketchannel, server, /127.0.0.1:43120 => /127.0.0.1:8555)
4116 [New I/O worker #35] DEBUG org.kaazing.mina.filter.codec.ProtocolCodecFilter  - Processing a MESSAGE_RECEIVED for session 4
4160 [New I/O worker #35] DEBUG transport.ssl.accept  - [ssl#4] EXCEPTION: (#00000004: kaazing niosocketchannel, server, /127.0.0.1:43120 => /127.0.0.1:8555): javax.net.ssl.SSLHandshakeException: SSL handshake failed.
4160 [New I/O worker #35] DEBUG transport.tcp.accept  - [tcp#4] EXCEPTION: (#00000004: kaazing niosocketchannel, server, /127.0.0.1:43120 => /127.0.0.1:8555): javax.net.ssl.SSLHandshakeException: SSL handshake failed.
4160 [New I/O worker #35] DEBUG transport.ssl.accept  - Error on SSL connection, closing connection: javax.net.ssl.SSLHandshakeException: SSL handshake failed.
4359 [New I/O worker #35] DEBUG transport.ssl.accept  - [ssl#4] CLOSED: (#00000004: kaazing niosocketchannel, server, /127.0.0.1:43120 => /127.0.0.1:8555)
4360 [New I/O worker #35] DEBUG transport.tcp.accept  - [tcp#4] CLOSED: (#00000004: kaazing niosocketchannel, server, /127.0.0.1:43120 => /127.0.0.1:8555)
4361 [New I/O worker #1] DEBUG org.kaazing.gateway.service.proxy.AbstractProxyHandler  - [5] session created ((#00000005: kzg ssl, client, ssl://localhost:9558 => ssl://localhost:9558))
4361 [New I/O worker #2] DEBUG performance.tcp  - AbstractNioWorker.process(Selector) took 651 ms: 1 reads, 0 writes
4361 [New I/O worker #1] DEBUG org.kaazing.gateway.service.proxy.AbstractProxyHandler  - [1->5] attaching sessions
4363 [New I/O worker #35] DEBUG transport.ssl.accept  - Error on SSL connection, closing connection: java.nio.channels.ClosedChannelException
4364 [New I/O worker #35] DEBUG performance.tcp  - AbstractNioWorker.process(Selector) took 247 ms: 1 reads, 0 writes
4368 [New I/O worker #1] DEBUG performance.tcp  - AbstractNioWorker.process(Selector) took 651 ms: 1 reads, 0 writes
4373 [New I/O worker #1] DEBUG transport.tcp.accept  - [tcp#1] CLOSED: (#00000001: kaazing niosocketchannel, server, /127.0.0.1:53681 => /127.0.0.1:9557)
4373 [New I/O worker #1] DEBUG org.kaazing.gateway.service.proxy.AbstractProxyHandler  - [1] session closed
4374 [New I/O worker #1] DEBUG org.kaazing.gateway.service.proxy.AbstractProxyHandler  - [1->5] detaching sessions
4376 [New I/O worker #1] DEBUG org.kaazing.gateway.service.proxy.AbstractProxyHandler  - [5] session closed
4380 [Time-limited test] WARN org.apache.mina.util.DefaultExceptionMonitor  - Unexpected exception.
java.lang.InterruptedException
	at org.jboss.netty.channel.group.DefaultChannelGroupFuture.await(DefaultChannelGroupFuture.java:202)
	at org.kaazing.mina.netty.ChannelIoAcceptor.dispose0(ChannelIoAcceptor.java:243)
	at org.kaazing.mina.core.service.AbstractIoService.dispose(AbstractIoService.java:308)
	at org.kaazing.gateway.transport.nio.AbstractNioAcceptor.dispose(AbstractNioAcceptor.java:460)
	at org.kaazing.gateway.transport.nio.NioSocketAcceptor.dispose(NioSocketAcceptor.java:138)
	at org.kaazing.gateway.server.context.resolve.DefaultTransportContext.dispose(DefaultTransportContext.java:106)
	at org.kaazing.gateway.server.context.resolve.DefaultGatewayContext.dispose(DefaultGatewayContext.java:124)
	at org.kaazing.gateway.server.Launcher.destroy(Launcher.java:138)
	at org.kaazing.gateway.server.test.Gateway.stop(Gateway.java:298)
	at org.kaazing.gateway.transport.ssl.Sslv3Test.connectSucceedsWithoutSslv3(Sslv3Test.java:280)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
4387 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Stopping server
4388 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Stopping services
4380 [New I/O worker #1] DEBUG transport.ssl.connect  - [ssl#3] CLOSED: (#00000003: kaazing niosocketchannel, client, /127.0.0.1:41603 => /127.0.0.1:9558)
4380 [New I/O worker #2] DEBUG transport.ssl.accept  - [ssl#2] CLOSED: (#00000002: kaazing niosocketchannel, server, /127.0.0.1:41603 => /127.0.0.1:9558)
4388 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  -   ssl://localhost:8555
4388 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Stopped services
4388 [New I/O worker #2] DEBUG transport.tcp.accept  - [tcp#2] CLOSED: (#00000002: kaazing niosocketchannel, server, /127.0.0.1:41603 => /127.0.0.1:9558)
4389 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Stopped server successfully in 0.028 secs at 2015-03-24 15:34:11
4388 [New I/O worker #1] DEBUG transport.tcp.connect  - [tcp#3] CLOSED: (#00000003: kaazing niosocketchannel, client, /127.0.0.1:41603 => /127.0.0.1:9558)
4392 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Stopping server
4392 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Stopping services
4392 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  -   ssl://localhost:9558
4392 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  -   tcp://localhost:9557
4392 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Stopped services
4393 [Time-limited test] INFO org.kaazing.gateway.server.Gateway  - Stopped server successfully in 0.020 secs at 2015-03-24 15:34:11

**Comment by cmebarrow** [comment]
The test timed out (5 sec timeout) during the call to stop the Gateway. 

Where do you see evidence of parallel test execution?

**Comment by jitsni** [comment]
From the log, the failed test  uses 9558 and 9557 ports. But before the failed test ends, there is one more test started the gateway at port 8555. The tests are run differently for ssl as we wanted to set a security property before JSSE is initialized. We specify forkCount=1 in surefire plugin config in transport.ssl/pom.xml

But my guess is that parallel execution may not be the issue here. There is some exception happened as you can see in the log, but the cause is not posted on the logs (4363 [New I/O worker #35] DEBUG transport.ssl.accept - Error on SSL connection, closing connection: java.nio.channels.ClosedChannelException)

See below interleaving of two gateways
--------------------
2826 [Time-limited test] INFO org.kaazing.gateway.server.Gateway - Starting services
2827 [Time-limited test] INFO org.kaazing.gateway.server.Gateway - ssl://localhost:9558
2827 [Time-limited test] INFO org.kaazing.gateway.server.Gateway - tcp://localhost:9557
...
4083 [Time-limited test] INFO org.kaazing.gateway.server.Gateway - Starting server
4083 [Time-limited test] INFO org.kaazing.gateway.server.Gateway - Starting services
4084 [Time-limited test] INFO org.kaazing.gateway.server.Gateway - ssl://localhost:8555
...
4388 [Time-limited test] INFO org.kaazing.gateway.server.Gateway - ssl://localhost:8555
4388 [Time-limited test] INFO org.kaazing.gateway.server.Gateway - Stopped services
...
4392 [Time-limited test] INFO org.kaazing.gateway.server.Gateway - Stopping services
4392 [Time-limited test] INFO org.kaazing.gateway.server.Gateway - ssl://localhost:9558
4392 [Time-limited test] INFO org.kaazing.gateway.server.Gateway - tcp://localhost:9557

**Comment by dpwspoon** [comment]
I believe these were fixed via launching jvm with separate propererties to allow SSLv3

**Comment by sbadugu** [comment]
This is passing now.
