### ISSUE TITLE
UDP max packet length is non configurable and is 1024 bytes

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/gateway#718]

**Comment by dpwspoon** [comment]
We have increased the default to 2048, but we should still provide a way to configure it

**Comment by sbadugu** [comment]
@jitsni Is this already fixed ?

**Comment by jitsni** [comment]
@sbadugu No, it is not fixed yet.

**Comment by sbadugu** [comment]
This is a feature request and not a bug, for future reference.

**Comment by dpwspoon** [comment]
We will not fix this unless asked to by a customer
