### ISSUE TITLE
Documentation "To Configure  Authorization" gives an incomplete list of services, should not include kerberos5.proxy

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#886]
Step 2 of [To Configure Authorization](https://kaazing.com/doc/5.0/security/p_authorization_configure/) says "The Gateway supports several types of services" and goes on to give an incomplete list of services ( for example proxy services not included). 

To reproduce:
- Go to https://kaazing.com/doc/5.0/security/p_authorization_configure/
- Scroll down to the section with header "To Configure Authorization"
- Read step 2. Observe that the list of services is 
  - balancer
  - broadcast
  - directory
  - echo
  - kerberos5.proxy

This list does not include the most commonly used service for Community Edition (proxy) and should not include kerberos5.proxy (because it does not make sense to require login to that service since it's a proxy to a Kerberos kdc. I think it would be preferable to remove the list and just rely on the link to Service Reference which is already given. At a minimum the "kerberos5.proxy" entry should be corrected to "proxy".

**Comment by michaelcretzman** [comment]
excellent point. this is now fixed:
https://kaazing.com/doc/5.0/security/p_authorization_configure/index.html

Thanks!

**Comment by cmebarrow** [comment]
Thanks @michaelcretzman
