### ISSUE TITLE
ConnectionManagementIT.clientWithPipeliningMustNotRetryPipeliningImmediatelyAfterFailure failure

### ISSUE THREAD

**Issue by StCostea** [kaazing/gateway#887]
After the fix in k3po of the script client.with.pipelining.must.not.retry.pipelining.immediately.after.failure/request, for issue https://github.com/k3po/k3po/issues/395, the test in gateway using this script is failing.

After a fast check with Wireshark, it seems that the gateway is answering to the first request `GET /request2 HTTP/1.1` with a `HTTP/1.1 200 OK`, which is not as expected. It looks like the problem is with the test code itself.

**Comment by StCostea** [comment]
This is a specification test for clients. It should not run on a server. Similarly, any test designed to test something on a server should not run on a client.

As discussed with David, we need to decide what to do with this type of tests: ignore, delete or comment out.

**Comment by Anisotrop** [comment]
Issue moved to [kaazing/tickets #1083](https://github.com/kaazing/tickets/issues/1083) via [**ZenHub**](https://www.zenhub.com/)
