### ISSUE TITLE
(to be removed)

### ISSUE THREAD

**Issue by daniel-smith-kaazing** [kaazing/gateway#911]
...

**Comment by robinzimmermann** [comment]
Out of curiosity, @daniel-smith-kaazing, did you specifically try a certificate with `clientAuth` for the client certificate and validate that it works in 4.x?

**Comment by daniel-smith-kaazing** [comment]
I am moving this issue to a private repo. It was filed here by mistake

**Comment by daniel-smith-kaazing** [comment]
closing. Filed by mistake.
