### ISSUE TITLE
[question] Is AMQP protocol on ActiveMQ broker supported?

### ISSUE THREAD

**Issue by archenroot** [kaazing/gateway#927]
We have 2 ActiveMQ, the standard one and Artemis, is any one of these brokers supported?

I plan to use AMQP protocol in microservice architecture, one microservice is UI. So what options for message broker selection I have with kaazing gateway? RabbitMQ only?

I understand this is issue tracker and not forum, but I tend to use github issue more and more as forum at the same time, if you don't mind.

**Comment by daniel-smith-kaazing** [comment]
Hi @archenroot - The Kaazing Gateway is compatible with version 0-9-1 of the AMQP protocol, so any AMQP broker that can use that version should be compatible. From what I understand, ActiveMQ is not compatible as it enforces the use of version 1.0: http://activemq.apache.org/amqp.html. Also Artemis is also not compatible, according to this: https://activemq.apache.org/artemis/docs/latest/using-AMQP.html

For future questions of this nature, we encourage you to utilize support.kaazing.com.

Regards,
Dan Smith @ Kaazing Global Support

**Comment by archenroot** [comment]
Hi @daniel-smith-kaazing  thanks for quick answer. That is clear. 

Regarding support: I know, I just tend to use github issues also as discussion place on my own project, but will keep this in mind.

Any plans on supporting 1.0 AMQP soon?

**Comment by robinzimmermann** [comment]
Hi @archenroot - AMQP 1.0 is in our future plans, yes, but we can't say anything about the timing just yet.
